backstopjs:
  async_compare_limit: '30'
  browser: chrome
  debug_mode: '0'
  mismatch_threshold: '0.00'
  resemble_output_options:
    error_type: movement
    transparency: '0.3'
    large_image_threshold: '1200'
    use_cross_origin: 1
    fallback_color: FF00FF
suite:
  location: remote
  binary_path: ''
  remote_locations: 'backstop_node:3000'
