version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.3-3.3.15
    container_name: "${PROJECT_NAME}_mariadb"
    # stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
  # volumes:
  #  - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
  #  - /path/to/mariadb/data/on/host:/var/lib/mysql # Use bind mount

  php:
    image: wodby/drupal-php:7.2-dev-4.11.0
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
      DOCKER_ENVIRONMENT: docker4drupal
      PROJECT_ENVIRONMENT: 'development'
      COLUMNS: 80 # Set 80 columns for docker exec -it.
    ## Read instructions at https://wodby.com/stacks/drupal/docs/local/xdebug/
    # PHP_XDEBUG: 1
    # PHP_XDEBUG_DEFAULT_ENABLE: 1
    # PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
    # PHP_IDE_CONFIG: serverName=my-ide
    # PHP_XDEBUG_REMOTE_HOST: host.docker.internal # Docker 18.03+ & Linux/Mac/Win
    # PHP_XDEBUG_REMOTE_HOST: 172.17.0.1 # Linux, Docker < 18.03
    # PHP_XDEBUG_REMOTE_HOST: 10.254.254.254 # macOS, Docker < 18.03
    # PHP_XDEBUG_REMOTE_HOST: 10.0.75.1 # Windows, Docker < 18.03
    volumes:
    - ./:/var/www/html
  ## For macOS users (https://wodby.com/stacks/drupal/docs/local/docker-for-mac/)
  # - ./:/var/www/html:cached # User-guided caching
  # - docker-sync:/var/www/html # Docker-sync
  ## For Xdebug profiler files
  # - files:/mnt/files

  nginx:
    image: wodby/nginx:1.15-5.3.0
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
    - php
    environment:
      NGINX_PAGESPEED: "on"
      NGINX_FASTCGI_INTERCEPT_ERRORS: "off"
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: drupal8
    volumes:
    - ./:/var/www/html
    labels:
    - 'traefik.backend=nginx'
    - 'traefik.port=80'
    - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}'

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    labels:
    - 'traefik.backend=mailhog'
    - 'traefik.port=8025'
    - 'traefik.frontend.rule=Host:mailhog.${PROJECT_BASE_URL}'

  traefik:
    image: traefik:1.7.7
    container_name: "${PROJECT_NAME}_traefik"
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
    - '${TRAEFIK_PORT}:80'
    # - '8080:8080' # Dashboard
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
